random_state: 0
current_year: 2024

run_component:
  ingestion: False
  etl: False
  etl_elo: False
  training: False
  tuning: False
  prediction: True
  bracketise: True
  submit_prediction: False
  importance: False
  run_server: False

etl:
  elo_k_factor: 32
  clutch_score_gap_max: 3
  538_start_year: 2016
  538_end_year: 2023
  form_game_window: 10
  form_game_similar: 3
  mens_training_start_year: 1985
  womens_training_start_year: 1985

model:
  mens_columns:
    - SeedA
    - SeedB
    - SeedDiff
    - EloWinProbA
    - WinRatioA
    - WinRatioB
    - ClutchRatioA
    - ClutchRatioB
    - FormHarmonicA
    - FormHarmonicB
    - FormUniformA
    - FormUniformB
    - Round
    - PtsForRatioA
    - PtsForRatioB
  womens_columns:
    - SeedA
    - SeedB
    - SeedDiff
    - EloWinProbA
    - WinRatioA
    - WinRatioB
    - ClutchRatioA
    - ClutchRatioB
    - FormHarmonicA
    - FormHarmonicB
    - FormUniformA
    - FormUniformB
    - Round
    - PtsForRatioA
    - PtsForRatioB
  optimisation_iterations: 10
  optimisation_initial: 2
  calibrate: False
  calibration_size: 0.2

predict:
  win_style: Prob
  num_brackets: 5

kaggle:
  competition: march-machine-learning-mania-2024
  submit_message: Test API Submission
  include_metric_in_message: False