random_state: 0
current_year: 2023

run_component:
  ingestion: False
  etl: False
  etl_elo: False
  training: False
  tuning: False
  prediction: False
  submit_prediction: True
  importance: False
  run_server: False

etl:
  elo_k_factor: 32
  clutch_score_gap_max: 3
  538_start_year: 2016
  538_end_year: 2023
  form_game_window: 10
  form_game_similar: 3
  mens_training_start_year: 2003
  womens_training_start_year: 1985

model:
  mens_columns:
    - SeedDiff
    - EloWinProbA
    - WinRatioA
    - WinRatioB
    - ClutchRatioA
    - ClutchRatioB
    - FormHarmonicA
    - FormHarmonicB
    - FormUniformA
    - FormUniformB
    - Round
    - MasseyMeanA
    - MasseyMeanB
    - MasseyMeanDiff
    - MasseyMedianA
    - MasseyMedianB
    - MasseyMedianDiff
    - MasseyStdA
    - MasseyStdB
  womens_columns:
    - SeedDiff
    - EloWinProbA
    - WinRatioA
    - WinRatioB
    - ClutchRatioA
    - ClutchRatioB
    - FormHarmonicA
    - FormHarmonicB
    - Round
  optimisation_iterations: 50
  optimisation_initial: 10
  calibrate: False
  calibration_size: 0.2

kaggle:
  competition: march-machine-learning-mania-2023
  submit_message: Note
  include_metric_in_message: False