name: march-madness-2023

channels:
 - conda-forge
 - defaults

dependencies:
 - python=3.10
 - pandas=1.5.2
 - kaggle=1.5.12
 - xgboost=1.7.1
 - ipykernel=6.20.2
 - bayesian-optimization=1.4.2
 - matplotlib=3.7.0
 - shap=0.41.0
 - dash=2.8.1
 - pyyaml=6.0